# Generated by Django 3.1.4 on 2021-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='telegraph_page',
            field=models.CharField(max_length=255, verbose_name='Telegra.ph page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name='Time publish'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='User name'),
        ),
    ]
