# Generated by Django 3.1.4 on 2021-01-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0003_auto_20210108_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.TextField(verbose_name='Text quote')),
                ('q_author', models.CharField(max_length=255, verbose_name='User name')),
                ('time', models.DateTimeField(verbose_name='Time publish')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
    ]
