# Generated by Django 3.1.4 on 2021-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0006_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='f_text',
            field=models.TextField(verbose_name='Текст факта'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='f_time',
            field=models.DateTimeField(verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_text',
            field=models.TextField(verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time',
            field=models.DateTimeField(verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bot_text',
            field=models.TextField(verbose_name='Текст бота'),
        ),
        migrations.AlterField(
            model_name='post',
            name='telegraph_page',
            field=models.CharField(max_length=255, verbose_name='Telegra.ph страница'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tg_uid',
            field=models.CharField(max_length=128, verbose_name='ID пользователя Telegram'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_field',
            field=models.DateTimeField(verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_text',
            field=models.TextField(verbose_name='Текст пользователя'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='q_author',
            field=models.CharField(max_length=255, verbose_name='Автор цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='q_text',
            field=models.TextField(verbose_name='Текст цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.DateTimeField(verbose_name='Время публикации'),
        ),
    ]
