# Generated by Django 3.1.4 on 2021-01-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0007_auto_20210110_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_stat', models.IntegerField(verbose_name='Стастика пользователей')),
                ('b_stat', models.IntegerField(verbose_name='Статистика бота')),
                ('st_time', models.DateTimeField(verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
            },
        ),
    ]
