# Generated by Django 3.1.7 on 2021-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0008_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='unique_id',
            field=models.CharField(max_length=32, null=True, verbose_name='Уникальный ID'),
        ),
    ]
