# Generated by Django 3.2.3 on 2021-06-06 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0008_auto_20210530_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('active', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=3, verbose_name='Активно')),
                ('chance', models.IntegerField(max_length=3, verbose_name='Шанс отображения (от 1 до 100)')),
                ('link_image', models.TextField(verbose_name='Ссылка на изображение')),
                ('link_site', models.TextField(verbose_name='Домен сайта (Пример - awse.us)')),
                ('utm_source', models.CharField(max_length=255, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(max_length=255, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(max_length=255, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(max_length=255, verbose_name='UTM Content')),
                ('utm_term', models.CharField(max_length=255, verbose_name='UTM Term')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('time_active', models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 3, 1, 121354, tzinfo=utc), verbose_name='Активно до')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 3, 1, 122354, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 3, 1, 49354, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 3, 1, 123355, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
