# Generated by Django 3.1.7 on 2021-03-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0009_facts_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='unique_id',
            field=models.CharField(max_length=32, null=True, verbose_name='Уникальный ID'),
        ),
    ]
