# Generated by Django 3.2.3 on 2021-06-06 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0010_auto_20210606_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 12, 21, 760231, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 12, 21, 760231, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='utm_campaign',
            field=models.CharField(default='null', max_length=255, verbose_name='UTM Campaign'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='utm_content',
            field=models.CharField(default='null', max_length=255, verbose_name='UTM Content'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='utm_medium',
            field=models.CharField(default='null', max_length=255, verbose_name='UTM Medium'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='utm_source',
            field=models.CharField(default='null', max_length=255, verbose_name='UTM Source'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='utm_term',
            field=models.CharField(default='null', max_length=255, verbose_name='UTM Term'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 12, 21, 685231, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 12, 21, 761225, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
