# Generated by Django 3.1.7 on 2021-03-30 12:57

from django.db import migrations, models
import my_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0010_quote_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='unique_id',
            field=models.CharField(default=my_web.models.random_string, max_length=32, null=True, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.CharField(default=my_web.models.random_string, max_length=32, null=True, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
