# Generated by Django 3.2.3 on 2021-06-06 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0011_auto_20210606_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 30, 10, 956278, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_site',
            field=models.CharField(max_length=255, verbose_name='Домен сайта (Пример - awse.us или awse.us/page/second_page)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 30, 10, 955277, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 30, 10, 879277, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 30, 10, 957278, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
