# Generated by Django 3.1.7 on 2021-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0012_auto_20210330_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unique_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
