# Generated by Django 3.1.7 on 2021-04-06 16:38

from django.db import migrations, models
import my_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0014_auto_20210330_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWARE_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Не удалось получить заголовок страницы', max_length=255, verbose_name='Название страницы')),
                ('page_html_code', models.TextField(default='<p>Ошибка парсинга страницы...</p>', verbose_name='HTML код страницы')),
                ('unique_id', models.CharField(default=my_web.models.random_string, max_length=32, unique=True, verbose_name='Уникальный ID')),
            ],
            options={
                'verbose_name': 'Страница AWARE',
                'verbose_name_plural': 'Страницы AWARE',
            },
        ),
    ]
