# Generated by Django 3.2 on 2021-04-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0016_auto_20210410_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='unique_id',
            field=models.CharField(default='dDkf0ZnH3Vucm32VMOMaFuLEXn6Z9ey8ei3', max_length=255, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='unique_id',
            field=models.CharField(default='JnEPDfSvePy_U', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_id',
            field=models.CharField(default='_2HYGIUWD7vd', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.CharField(default='n_2WK6C8STmoFH', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
