# Generated by Django 3.2 on 2021-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0017_auto_20210410_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='unique_id',
            field=models.CharField(default='MR3Wf61mfJZLX62i', max_length=255, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='unique_id',
            field=models.CharField(default='udRcIolIU3hGv7Q', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_id',
            field=models.CharField(default='znLBCMc6PDA6', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.CharField(default='tCbJmA-Wk5RBrw7', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
