# Generated by Django 3.2 on 2021-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0018_auto_20210410_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='unique_id',
            field=models.CharField(default='W-Hh_oCvtSHPQskHkah', max_length=255, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='unique_id',
            field=models.CharField(default='PKfEdBUie21fmMe', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_id',
            field=models.CharField(default='9stufrVTru0I', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.CharField(default='ZxGYSYQndcBZfR', max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
