# Generated by Django 3.2 on 2021-04-11 10:55

from django.db import migrations, models
import my_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0020_auto_20210411_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='unique_id',
            field=models.CharField(default=my_web.models.random_string, max_length=255, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='unique_id',
            field=models.CharField(default=my_web.models.random_string, max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_id',
            field=models.CharField(default=my_web.models.random_string, max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.CharField(default=my_web.models.random_string, max_length=32, unique=True, verbose_name='Уникальный ID'),
        ),
    ]
