# Generated by Django 3.2 on 2021-04-11 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0021_auto_20210411_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.date(2021, 4, 11), verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
