# Generated by Django 3.2 on 2021-04-11 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0022_aware_page_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='f_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_field',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время обновления'),
        ),
    ]
