# Generated by Django 3.2 on 2021-04-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0023_auto_20210411_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facts',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
