# Generated by Django 3.2 on 2021-04-29 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0025_auto_20210429_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 16, 44, 15, 837895, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 16, 44, 15, 746890, tzinfo=utc), verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 16, 44, 15, 838895, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
