# Generated by Django 3.2.1 on 2021-05-04 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0027_auto_20210502_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 17, 11, 15, 859918, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 17, 11, 15, 810199, tzinfo=utc), verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 17, 11, 15, 860340, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
