# Generated by Django 3.2 on 2021-05-08 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0028_auto_20210504_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='i_chance',
            field=models.IntegerField(default=50, max_length=3, verbose_name='Шанс отображения (от 1 до 100)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 17, 11, 45, 430658, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 17, 11, 45, 621878, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 17, 11, 45, 430658, tzinfo=utc), verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 17, 11, 45, 622877, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
