# Generated by Django 3.2 on 2021-05-09 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0029_auto_20210508_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='i_time',
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 45, 55, 360162, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 45, 55, 197916, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_title',
            field=models.CharField(default='Рекламная запись', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 45, 55, 361166, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
