# Generated by Django 3.2 on 2021-05-09 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0030_auto_20210509_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='i_language',
            field=models.CharField(choices=[('ua', 'Украинский'), ('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=2),
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 52, 9, 406717, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 52, 9, 317715, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 52, 9, 407717, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
