# Generated by Django 3.2.2 on 2021-05-09 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0032_auto_20210509_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 13, 49, 6, 543338, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 13, 49, 6, 456333, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 13, 49, 6, 544334, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
