# Generated by Django 3.2.6 on 2021-08-30 20:34

import awse.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSE_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Failed to get page title', max_length=255, verbose_name='Page title')),
                ('page_html_code', models.TextField(default='<p>Page parsing error ...</p>', verbose_name='HTML code of the page')),
                ('unique_id', models.CharField(default=awse.models.random_string, max_length=255, unique=True, verbose_name='Unique ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 8, 30, 20, 34, 12, 699058, tzinfo=utc), verbose_name='Time of creation')),
            ],
            options={
                'verbose_name': 'AWSE page',
                'verbose_name_plural': 'AWSE Pages',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='Actively')),
                ('chance', models.IntegerField(max_length=3, verbose_name='Display chance (1 to 100)')),
                ('link_image', models.TextField(verbose_name='Image link')),
                ('link_site', models.CharField(max_length=255, verbose_name='Site domain (Example - awse.us or awse.us/page/second_page)')),
                ('utm_source', models.CharField(default='null', max_length=255, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(default='null', max_length=255, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(default='null', max_length=255, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(default='null', max_length=255, verbose_name='UTM Content')),
                ('utm_term', models.CharField(default='null', max_length=255, verbose_name='UTM Term')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Views')),
                ('time_active', models.DateTimeField(default=datetime.datetime(2021, 8, 30, 20, 34, 12, 698826, tzinfo=utc), verbose_name='Active until')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='BlackWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Word')),
                ('ano_mode', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='Anagram')),
            ],
            options={
                'verbose_name': 'Black word',
                'verbose_name_plural': 'Black words',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_text', models.TextField(verbose_name='Text')),
                ('i_language', models.CharField(choices=[('ua', 'Ukrainian'), ('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Language')),
                ('i_active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='Actively')),
                ('i_chance', models.IntegerField(max_length=3, verbose_name='Display chance (1 to 100)')),
                ('i_views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Views')),
                ('i_time_active', models.DateTimeField(default=datetime.datetime(2021, 8, 30, 20, 34, 12, 676175, tzinfo=utc), verbose_name='Active until')),
            ],
            options={
                'verbose_name': 'Advertising record',
                'verbose_name_plural': 'Advertising records',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_stat', models.IntegerField(verbose_name='User statistics')),
                ('b_stat', models.IntegerField(verbose_name='Bot statistics')),
                ('st_time', models.DateTimeField(default=datetime.datetime(2021, 8, 30, 20, 34, 12, 699409, tzinfo=utc), verbose_name='Update time')),
            ],
            options={
                'verbose_name': 'Bot statistics',
                'verbose_name_plural': 'Bot statistics',
            },
        ),
    ]
