# Generated by Django 3.2.7 on 2021-10-21 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awse_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 15, 52, 27, 824752, tzinfo=utc), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 15, 52, 27, 824511, tzinfo=utc), verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 15, 52, 27, 807280, tzinfo=utc), verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 15, 52, 27, 825094, tzinfo=utc), verbose_name='Update time'),
        ),
    ]
