# Generated by Django 3.2.3 on 2021-06-06 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awse', '0009_auto_20210606_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 7, 23, 749914, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_site',
            field=models.CharField(max_length=255, verbose_name='Домен сайта (Пример - awse.us)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 7, 23, 748914, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 7, 23, 675921, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 18, 7, 23, 750914, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
