# Generated by Django 3.2.3 on 2021-06-10 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awse', '0012_auto_20210606_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 17, 3, 49, 437050, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 17, 3, 49, 436045, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 17, 3, 49, 364051, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 17, 3, 49, 438049, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
