# Generated by Django 3.2.3 on 2021-06-11 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awse', '0014_auto_20210611_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 14, 47, 10, 548780, tzinfo=utc), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 14, 47, 10, 548780, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 14, 47, 10, 477328, tzinfo=utc), verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 14, 47, 10, 549780, tzinfo=utc), verbose_name='Время обновления'),
        ),
    ]
