# Generated by Django 3.2.4 on 2021-06-30 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import awse.models


class Migration(migrations.Migration):

    dependencies = [
        ('awse', '0015_auto_20210611_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aware_page',
            options={'verbose_name': 'AWARE page', 'verbose_name_plural': 'AWARE Pages'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='blackword',
            options={'verbose_name': 'Black word', 'verbose_name_plural': 'Black words'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Advertising record', 'verbose_name_plural': 'Advertising records'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Bot statistics', 'verbose_name_plural': 'Bot statistics'},
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='page_html_code',
            field=models.TextField(default='<p>Page parsing error ...</p>', verbose_name='HTML code of the page'),
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 19, 56, 55, 710543, tzinfo=utc), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='title',
            field=models.CharField(default='Failed to get page title', max_length=255, verbose_name='Page title'),
        ),
        migrations.AlterField(
            model_name='aware_page',
            name='unique_id',
            field=models.CharField(default=awse.models.random_string, max_length=255, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='Actively'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='chance',
            field=models.IntegerField(max_length=3, verbose_name='Display chance (1 to 100)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_image',
            field=models.TextField(verbose_name='Image link'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_site',
            field=models.CharField(max_length=255, verbose_name='Site domain (Example - awse.us or awse.us/page/second_page)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 19, 56, 55, 709542, tzinfo=utc), verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='blackword',
            name='ano_mode',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='Anagram'),
        ),
        migrations.AlterField(
            model_name='blackword',
            name='word',
            field=models.CharField(max_length=255, unique=True, verbose_name='Word'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_active',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='Actively'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_chance',
            field=models.IntegerField(max_length=3, verbose_name='Display chance (1 to 100)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_language',
            field=models.CharField(choices=[('ua', 'Ukrainian'), ('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_time_active',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 19, 56, 55, 634542, tzinfo=utc), verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='info',
            name='i_views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='b_stat',
            field=models.IntegerField(verbose_name='Bot statistics'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='st_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 19, 56, 55, 711537, tzinfo=utc), verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='u_stat',
            field=models.IntegerField(verbose_name='User statistics'),
        ),
    ]
